---
- name: Start Galera container (non-bootstrap nodes or post-bootstrap)
  community.docker.docker_container:
    name: galera
    image: mariadb:{{ mariadb.version }}
    restart_policy: always
    env:
      MARIADB_ROOT_PASSWORD: "{{ galera_root_password }}"
    volumes:
      - /var/lib/mysql:/var/lib/mysql:rw
      - /etc/mariadb:/etc/mysql/conf.d
    network_mode: host
    state: started

- name: Wait
  ansible.builtin.wait_for:
    port: 3306
    delay: 20
    timeout: 150
    host: "{{ ansible_host }}"
